### ISSUE TITLE
Add a max width for images

### ISSUE THREAD

**Issue by thehowl** [go-gitea/theme#48]
Currently, images will overflow from the post if they're bigger than it is. The simple fix is to add this to the CSS

```css
img {
  max-width: 100%;
}
```
